class LocatorButton:
    logotip = '//*[@alt="Емолл"]'
    search_input = '//*[@enterkeyhint="search"]'
    search_button = '//*[@aria-label="Начать поиск"]'
    catalog_button = '//*[@class="catalog_button__yhaM7"]'
    action_button_enter = '//*[@href="https://emall.by/login?backurl=/?srsltid=AfmBOopzz7KRzWCgKbuaGNTcyQwF6Ud_ZAFxrcwDh5jL9RFEeicsep06"]'
    action_button_orders = '//*[@href="https://emall.by/orders"]'
    action_button_favorites = '//*[@href="https://emall.by/favorites"]'
    action_button_basket = '//*[@href="https://emall.by/cart"]'
    actions_button = '//*[@href="https://emall.by/actions"]'
    lucky_goods_button = '// *[ @ href = "https://emall.by/actions/lucky-goods"]'
    promocodes_button = '//*[@//*[@href="https://emall.by/actions/promocodes"]'
    new_button = '//*[@href="https://emall.by/actions/new"]'
    urgent_goods_button = '//*[@href="https://emall.by/actions/urgent-goods"]'
    take_more_button = '//*[@href="https://emall.by/actions/take-more"]'
    naushniki_besprovodnye_button = '// *[ @ href = "https://emall.by/category/naushniki-besprovodnye"]'
    school_button = '//a[@href="https://emall.by/actions/school-supplies"] [@class="links_links__a__Yxalk"]'
    detskaya_stirka = '//a[@href="https://emall.by/category/4006"] '
